### ISSUE TITLE
Information on how to run the plugin.

### ISSUE THREAD

**Issue by capitantrueno** [kisstkondoros/codemetrics-idea#1]
I've installed this plugin and I'm trying to use it with the default settings. But, unfortunately, there are no annotations in my code. Any advice to run it?
Thanks a lot!

**Comment by kisstkondoros** [comment]
The plugin only works inside java files and it should show traffic light indicators on the gutter (next to the line number indicators). You shouldn't run it explicitly, it should be automatically updated on text changes.

**Comment by capitantrueno** [comment]
Thank you for your reply. 
My intention was to use it to get metrics from my typescript files. But by your comment, I understand that only the Java language is supported.
Best regards!
