### ISSUE TITLE
Not showing Cyclometric complexity of test classes

### ISSUE THREAD

**Issue by nagkumar** [kisstkondoros/codemetrics-idea#15]
<img width="825" alt="image" src="https://github.com/kisstkondoros/codemetrics-idea/assets/332234/6ddc9c9b-6d6c-4446-9f79-4da00ef0016e">

Is there any configuration that enables it to show the complexity of the test case code too?

**Comment by kisstkondoros** [comment]
Set option "Show metrics above complexity" to 0
