### ISSUE TITLE
can't get some dependencies(run project)

### ISSUE THREAD

**Issue by jsmzr** [kisstkondoros/codemetrics-idea#5]
I am trying to run the project on my IDEA and I can't get some dependencies. It may be better to develop plugin using the gradle management dependencies

**Comment by kisstkondoros** [comment]
There are no external dependencies, gradle would be an overkill at this point IMO.
Please check https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/setting_up_environment.html for details on how to set up your environment.

**Comment by jsmzr** [comment]
This is a good suggestion, but I'm sure I'm using the IDEA plugin development environment, and there are still some dependencies that can't be found.
**com.intellij.psi.PsiElement** is ok
**com.google.common.base.Suppliers**(from google-collections?) and **com.intellij.psi.PsiClass** still not found
My version is IntelliJ IDEA Community Edition IC-182.4505.22

**Comment by kisstkondoros** [comment]
In that case, sorry, I'll have a deeper look into it.

**Comment by kisstkondoros** [comment]
The minimum required version is 191 (2019.1), could you please check with that version?

**Comment by kisstkondoros** [comment]
It could also be related to the JDK version.

Sorry but I'm not at my PC. I can only check it later in depth.

**Comment by jsmzr** [comment]
Thank you very much, this plugin is excellent. I try to learn more and extend some features on top of it.
I will try to use gradle to switch between other IDEA versions.

**Comment by jsmzr** [comment]
When I switched to **2019.1** and joined guava, I successfully solved this problem.

Maybe Idea openapi removed some class files.

```groovy
// build.gradle
dependencies {
    compile 'com.google.guava:guava:28.1-jre'
}

// See https://github.com/JetBrains/gradle-intellij-plugin/
intellij {
//    version '2019.2.3'
    version '2019.1'
}
```

**Comment by kisstkondoros** [comment]
That could very well be...

If you haven't planned to roll your own plugin, feel free to open a PR for your changes! If they align with the goals of mine, you can be sure that I'll merge it.

Have fun with your experiments!
